CREATE DATABASE IF NOT EXISTS 3at_db;
USE 3at_db;

CREATE TABLE IF NOT EXISTS aluno1 (

numero_chamada INT PRIMARY KEY,
nome VARCHAR(50)
);

DELIMITER $$

CREATE PROCEDURE IF EXISTS CadastrarAluno1(
    IN p_chamada INT,
    IN p_nome VARCHAR(50)
)
BEGIN
INSERT INTO aluno1 (numero_chamada, nome)
VALUES (p_chamada, p_nome);
END $$
DELIMITER ;
CALL CadastrarAluno1(1, 'GUSTAVO ALAIKO DE ABREU');
CALL CadastrarAluno1(2, 'EDUARDO AUGUSTO KLAVA CORREA');
CALL CadastrarAluno1(3, 'DANIEL BIEHL STIWERS');
CALL CadastrarAluno1(4, 'ISABELLA CASSILHA SIPPEL');
CALL CadastrarAluno1(5, 'SARAH CHAVES DE OLIVEIRA');
CALL CadastrarAluno1(7, 'MIGUEL DA COSTA MOREIRA');
CALL CadastrarAluno1(8, 'RYAN DA VEIGA GOLUBIEWSKI');
CALL CadastrarAluno1(9, 'LORENZO DE OLIVEIRA SANCHES');
CALL CadastrarAluno1(10, 'SOFIA DE SOUZA CORDEIRO');
CALL CadastrarAluno1(11, 'ARTHUR FERNANDO LORENZINI');
CALL CadastrarAluno1(12, 'RAPHAELA FERREIRA MARTINS ALVES DA PAZ');
CALL CadastrarAluno1(13, 'GEOVANNA GABRIELLY DE ASSUNCAO');
CALL CadastrarAluno1(114, 'PEDRO GALEAZZI ZEQUIN');
CALL CadastrarAluno1(15, 'GABRIEL GARCIA BLASKEVICZ DUBIEL');
CALL CadastrarAluno1(16, 'JEAN GONCALVES');
CALL CadastrarAluno1(17, 'LUCAS GONCALVES');
CALL CadastrarAluno1(18, 'RAFAEL GUILHERME STRYK DE SOUZA');
CALL CadastrarAluno1(19, 'JOAO GUILHERME WEBER DA SILVA');
CALL CadastrarAluno1(20, 'MATHEUS HENRIQUE DA GAMA VOI');
CALL CadastrarAluno1(21, 'GABRIEL HENRIQUE MACEDO GRACIOLI');
CALL CadastrarAluno1(22, 'JOAO HENRIQUE MARTINS MACHADO FILHO');
CALL CadastrarAluno1(23, 'GABRIEL IVNUK CAVALCANTE');
CALL CadastrarAluno1(24, 'YAN KNEIF RENART');
CALL CadastrarAluno1(25, 'GABRIEL KORB MILANEZ');
CALL CadastrarAluno1(26, 'NICOLAS DESIDERIO OLIVEIRA');
CALL CadastrarAluno1(27, 'WESLEY LEAL DE SOUZA');
CALL CadastrarAluno1(28, 'KAUA LEMES RAMOS');
CALL CadastrarAluno1(29, 'GABRIEL LINDER PATRICIO');
CALL CadastrarAluno1(30, 'OTTO MIGUEL DE MORAES');
CALL CadastrarAluno1(31, 'YAGO OVIDIO DOS SANTOS');
CALL CadastrarAluno1(32, 'JOAO PEDRO SAVARIS MACHADO');
CALL CadastrarAluno1(33, 'NICOLE TEIXEIRA MAZZE');
CALL CadastrarAluno1(34, 'ARTHUR VINICIUS GOMES LOURENCO');
CALL CadastrarAluno1(35, 'ANA VITORIA LEAL KEDROSKI');
CALL CadastrarAluno1(36, 'JANAINA VITORIA VITOR DE OLIVEIRA');
CALL CadastrarAluno1(37, 'FLAVIA WACHTER BUZZATTO');
CALL CadastrarAluno1(38, 'EDUARD ZAYON PORTELA SUICA DOS SANTOS');

SELECT * FROM alunos;
